"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";

type SharedData = {
  project: { plot: string; city: string; type: string; area: number; cost: number; costPerSqft: number; spec: string };
  quantities: { steel: number; cement: number; bricks: number };
  chart: Array<{ label: string; amount: number; pct: number; color: string }>;
};

export default function SharePage() {
  const params = useParams<{ id: string }>();
  const [data, setData] = useState<SharedData | null>(null);

  useEffect(() => {
    const raw = localStorage.getItem(`builddocs-share-${params.id}`);
    if (raw) setData(JSON.parse(raw) as SharedData);
  }, [params.id]);

  const hasData = useMemo(() => Boolean(data), [data]);

  if (!hasData) {
    return (
      <main className="mx-auto max-w-3xl px-4 py-16 text-center">
        <h1 className="text-2xl font-semibold">Share not found</h1>
        <p className="mt-2 text-gray-600">This shared summary is unavailable on this device.</p>
        <Link href="/" className="mt-4 inline-block rounded-lg bg-primary px-4 py-2 font-semibold text-white">
          Create your own estimate
        </Link>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-5xl px-4 py-10">
      <div className="rounded-2xl border bg-white p-6 shadow-sm">
        <h1 className="text-2xl font-semibold">Project Summary</h1>
        <p className="mt-2 text-sm text-gray-600">
          {data!.project.type} | {data!.project.area} sqft | {data!.project.city} | {data!.project.spec}
        </p>
        <p className="mt-2 text-lg font-semibold">
          {data!.project.cost.toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 })}{" "}
          <span className="text-sm font-medium text-gray-600">({data!.project.costPerSqft}/sqft)</span>
        </p>

        <div className="mt-6 rounded-xl border p-4">
          <h3 className="font-semibold">Cost Breakdown</h3>
          <div className="mt-3 space-y-2">
            {data!.chart.map((row) => (
              <div key={row.label}>
                <div className="mb-1 flex justify-between text-sm">
                  <span>{row.label}</span>
                  <span>
                    {row.amount.toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 })} (
                    {row.pct.toFixed(1)}%)
                  </span>
                </div>
                <div className="h-2 rounded-full bg-gray-100">
                  <div className={`h-2 rounded-full ${row.color}`} style={{ width: `${Math.max(2, row.pct)}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-6 grid gap-3 md:grid-cols-3">
          <div className="rounded-lg border p-3">Steel: {Math.round(data!.quantities.steel).toLocaleString("en-IN")} kg</div>
          <div className="rounded-lg border p-3">Cement: {Math.round(data!.quantities.cement).toLocaleString("en-IN")} bags</div>
          <div className="rounded-lg border p-3">Bricks: {Math.round(data!.quantities.bricks).toLocaleString("en-IN")} nos</div>
        </div>

        <div className="mt-8 rounded-lg bg-blue-50 p-4 text-center">
          <p className="font-medium">Generated by BuildDocs.ai — Create your own estimate free</p>
          <Link href="/" className="mt-3 inline-block rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">
            Start Free
          </Link>
        </div>
      </div>
    </main>
  );
}

